### ISSUE TITLE
After the update, all the buildings from this mod in the campaign were removed

### ISSUE THREAD

**Issue by dima64272** [MQ-1175/more-vanilla#15]
I reinstalled the mod, and all the buildings were removed, and those under construction turned into air.

**Comment by MQ-1175** [comment]
check README. i have to rename all blocks because it was messy in the block list, so it's just basicly replace all the old one. Apologize if it broke a lot during campaign

**Comment by MQ-1175** [comment]
wait dont on yeah i see the problem here, thank for telling me
