### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Notcreativenickname** [MQ-1175/more-vanilla#7]
1. Mk 3 non powered drill (same size, +10% speed, mines thorium)
2. Mk 3 powered drill (+1 size, +25% speed, boosted with cryofluid, +20% boost power)
3. Mk 2 cultivator (+1 size, +500% output, +700% water input, -75% speed)
4. Mk 3 cultivator (+1 size, + 40% output, +10% water input, +5% speed)
(+X% is from previous tier)
And i have a question about future content plans.
Will you add Mk2,3 power blocks?

**Comment by MQ-1175** [comment]
power blocks are under work, those blocks in drill sector too. it might take a lot of time

**Comment by Notcreativenickname** [comment]
> power blocks are under work, those blocks in drill sector too. it might take a lot of time

You mean spriting or coding. 
Because i will happily accept unsprited ones for "balance testing".
